### ISSUE TITLE
You might want to format your table...

### ISSUE THREAD

**Issue by PerfectCarl** [quassy/elementary-apps#1]
... using ref link

```
this is [a link][1]
[1]: http://www.google.com
```

And format the doc using http://www.tablesgenerator.com/markdown_tables

I tried to contribute to apps file but after some time I was a bit lost.

Nice looking page and great initiative

**Comment by quassy** [comment]
My plan is that the table gets automatically generated by posts like [this](http://quassy.github.io/elementary-apps/Foto/) ([code](https://raw.githubusercontent.com/quassy/elementary-apps/gh-pages/_posts/2014-10-20-Foto.md)) once I have added all apps as posts. Might take a while ;) but after that reformatting the table itself should be easier as one would only have to edit one template. And contributions should become easier ([template](https://github.com/quassy/elementary-apps/blob/gh-pages/_posts/1970-01-01-Template.md)).

**Comment by PerfectCarl** [comment]
Generation. Fancy!

Funny I did that too a while ago.
Well sort of.

(Not as good looking or cool)

I generated [this page](https://github.com/PerfectCarl/awesome-play1) from a google spreadsheet (and some macro love)

**Comment by quassy** [comment]
That's a looong list... Google Spreadsheet has macros?

[Fancy list](http://quassy.github.io/elementary-apps/list/apps/) is more or less ready :)

**Comment by quassy** [comment]
[New list (old URL)](http://quassy.github.io/elementary-apps/apps/) is now shipping, that should make adding new apps much easier.
