### ISSUE TITLE
iViewer image and download info

### ISSUE THREAD

**Issue by Philip-Scott** [quassy/elementary-apps#10]
First of all, thank you for adding my app! I guess it's not really a bug, but if it's not too much o a bother, would you mind changing the screenshot to the one i used here? :) https://github.com/Philip-Scott/iViewer

Also since first shared the app, i made a github page for it... so if you could also update that it would be awesome!

**Comment by quassy** [comment]
I have changed the screenshot and also added your GitHub page. Thanks for your input, any (literally!) feedback is appreciated! 

You should add a LICENSE file to your GitHub repo, I think I only found the license info by digging deep into your code ;)

**Comment by Philip-Scott** [comment]
Honestly, i think a mayor thing that's missing are screenshots, but i see that you guys are working on that ;) I'll look into helping you guys with a couple of shots in the next days :) 

But hey, the link to the github page is broken, it's currently linking to "http://quassy.github.io/elementary-apps/iViewer/Philip-Scott/iViewer" instead of https://github.com/Philip-Scott/iViewer :)

**Comment by quassy** [comment]
You answered too quick, commit 8f8ce6cf84 already fixed that ;)

More screenshots would really be nice! I try to install some new apps from time to time but it is quite time-consuming as I currently only have a VirtualMachine.
