### ISSUE TITLE
Use a more suitable base system / CMS

### ISSUE THREAD

**Issue by quassy** [quassy/elementary-apps#11]
Jekyll was intended as a blogging platform, elementary apps is turning more and more into a database / (window shopping) app store / maybe some day review site. elementary apps should be based on a dynamic, interactive, common system to manage content and invite user contributions...

**Comment by orschiro** [comment]
@quassy 

Maybe something to be discussed along the line of the new, planned eOS software center. This is what I found on the eOS Blog:

![image](https://cloud.githubusercontent.com/assets/170947/7082455/c6ab4696-df54-11e4-8103-3715665b0130.png)

**Comment by quassy** [comment]
Yes, in an ideal world my site would basically be the web version of / web frontend to AppCenter, but as AppCenter will not arrive before elementary Freya+1 / Loki the wait just seems too long.

**Comment by orschiro** [comment]
- An open wiki with template use maybe?
- Or Wordpress + specific plugins?

**Comment by quassy** [comment]
Yes, I thought about using Gollum (git-based wiki which is also used for the GitHub Wiki system) because I wanna keep version control, plain text and the ability for people to make pull requests. Have to try it out some day...
