### ISSUE TITLE
Adding Messenger to PPA

### ISSUE THREAD

**Issue by orschiro** [quassy/elementary-apps#15]
Hi @quassy,

Do you have experience with packaging for a PPA?

Aluxian has [released](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/13#issuecomment-93359808) a .deb package for his Facebook Messenger App that perfectly integrates into the eOS desktop. I don't have experience in packaging for a PPA myself, do you?

**Comment by quassy** [comment]
Thanks for the report! 

I don't, hence I thought the best idea would be to forward this to the semi official PPA of elementary apps ;). [See issue #5 on SomeElementary](/SomeElementary/PPA-Issues/issues/5). I plan to add all packages from that PPA to elementary apps.

**Comment by kennyh7279** [comment]
and I plan on adding all the app from elementary apps to the ppa, it's like some sort of symbiotic relationship

**Comment by quassy** [comment]
Regarding adding Messenger to the list: I'm not sure I want to add Messenger to this collection as it does not feel like an _elementary app_ at all, it is _only_ a web wrapper. So closing this for now. 

If anyone disagrees feel free to change my mind, I don't want anyone forking just because I'm stupid. Forks are evil.

**Comment by orschiro** [comment]
@quassy 

Maybe it is wise to think about a set of selection criteria to better define what `A resource for 3rd party software designed for elementary (OS)` means (taken from the about page).

For example:
- Does it have to use Vala?
- Does it have to integrate tightly into the system settings?
- Does it have to be created specifically for eOS or also other distributions?
