### ISSUE TITLE
Categories are broken, tags are stupid

### ISSUE THREAD

**Issue by quassy** [quassy/elementary-apps#18]
Guess it's because I messed-up lower / upper case. Yet another limitation of Jekyll (for this particular purpose)...
- [ ] Fix categories
- [x] Consider hiding tags because they are too painful to maintain

**Comment by inputsh** [comment]
Maybe it would be useful to add _something_ (a tag, a category, a button, whatever) that will serve like an information about the current state of the project's development?

So, for example, `Writer` still has a long way to go until it gets to the beta version, so it might be useful to have something like `Build` to let the users know that the project is in its early development. If the project is currently in its beta stage, then it would say `Beta`. If the project is stable, it should say `Stable`.

It could be a simple way of letting the visitors know should they install the application right now or not.

**Comment by quassy** [comment]
I see your point. I have been thinking back and forth about this for some time, see also #24 (updated a few seconds ago). On one hand users will be confused / annoyed when they install stuff like Writer which feels very inmature, on the other hand I'm not sure I can keep up with ~90 apps / pieces of art. (Some in-mature in-active projects already got hidden.) I'm quite open to suggestions what's the best way to do it.

This bug was originally an expression of my frustration with Jekyll (or rather in this case GitHub Pages lacking the needed functionaility which Jekyll has) for this feature :D
