### ISSUE TITLE
Whishlist: .epub Reader

### ISSUE THREAD

**Issue by inputsh** [quassy/elementary-apps#31]
I really think that Linux (and elementary OS) lacks a good `.epub` reader. Evince (Document Viewer) does a great job of supporting `.pdf`files, but it looks like `.epub` format is not planned (judging by this [source](https://wiki.gnome.org/Apps/Evince/Roadmap)).

**Comment by inputsh** [comment]
[GNOME Books](https://github.com/martamilakovic/gnome-books) might be a good place to start.

**Comment by inputsh** [comment]
Relevant Launchpad bug: https://bugs.launchpad.net/elementaryos/+bug/1183708

**Comment by quassy** [comment]
I will add it to the list when I find the time :)

There are so many great / important ideas out there, sad there is such a lack of man power. If only Gnome and elementary had more similar HIGs.
