### ISSUE TITLE
Some new app can be added to the list

### ISSUE THREAD

**Issue by choyan** [quassy/elementary-apps#4]
Footnote:
https://launchpad.net/footnote

Photostream:
https://github.com/serge1peshcoff/photostream

Focus:
https://launchpad.net/focus-app

Indicator USB:
http://entornosgnulinux.com/2014/10/12/indicator-usb-en-elementary-os-y-ubuntu/

Synopsis:
https://launchpad.net/synopsis

Fantasy Book reader:
https://code.launchpad.net/fantasy

**Comment by quassy** [comment]
Thanks for your input, I will add these shortly to the list. With the exception of Indicator USB which seems to be quite outdated.

**Comment by quassy** [comment]
Thanks again, the apps are now available on the [new list](http://quassy.github.io/elementary-apps/apps/).
