### ISSUE TITLE
Wishlist: Stopwatch Timer

### ISSUE THREAD

**Issue by orschiro** [quassy/elementary-apps#41]
Hi all, 

Is someone aware of a simple stopwatch timer application in the eOS design? 

I could imagine something like the following: 

![image](https://cloud.githubusercontent.com/assets/170947/8478662/1fdc0010-20d3-11e5-9649-c50642f154f4.png)

Warmly,

Robert

**Comment by quassy** [comment]
Have you tried [Gnome Clocks](https://apps.ubuntu.com/cat/applications/gnome-clocks/)? (If it works well, could you make screenshot on elementary?)

**Comment by orschiro** [comment]
@quassy 

Thanks for the suggestion. Gnome Clocks works well on eOS:

![image](https://cloud.githubusercontent.com/assets/170947/8639897/e33a2df0-28e6-11e5-8efa-6338e1839284.png)

However, I find [Tea Time](http://www.rojtberg.net/419/intruducing-teatime/) even better for the following reasons:
- Its dock icon shows the progress of the countdown
- It allows me to define and store custom timers.

![image](https://cloud.githubusercontent.com/assets/170947/8639909/fed6bdda-28e6-11e5-97ea-5f8fab6c678a.png)

**Comment by quassy** [comment]
Thanks for the feedback! I'll try to take a look myself, but it looks pretty old / GTK2.

**Comment by quassy** [comment]
[Hourglass](https://plus.google.com/116278520866308650044/posts/B1VoqtEjvaT)

**Comment by orschiro** [comment]
> Hourglass

This looks cool! Thanks for sharing.

**Comment by quassy** [comment]
I have added Hourglass to the site as it seems to be the "most elementarian" app out there...
