### ISSUE TITLE
Translator source code

### ISSUE THREAD

**Issue by orschiro** [quassy/elementary-apps#45]
Hi all, 

Where can I find the source code of [Translator](https://quassy.github.io/elementary-apps/Translator/)?

Thankfully,

Robert

**Comment by quassy** [comment]
Only on the developers [personal Launchpad site](https://code.launchpad.net/~grabli66-r/+junk/translator). 

`bzr branch lp:~grabli66-r/+junk/translator`

**Comment by orschiro** [comment]
Thanks @quassy!

**Comment by quassy** [comment]
Are you planning on forking it? :)

**Comment by orschiro** [comment]
Nope. :)

I was just interested in knowing what the software is using as the translation backend. It's Yandex. 

Plus, I wanted to ask the developer if he can add Dutch language support which he did! :)
