### ISSUE TITLE
none of the listed PPAs for the eradio app seem to be working

### ISSUE THREAD

**Issue by sysfu** [quassy/elementary-apps#59]
Tried all three & no love.

`Cannot add PPA: 'ppa:justsomedood/justsomeelementary'.
Please check that the PPA name or format is correct.`

```
W: Failed to fetch http://ppa.launchpad.net/dreamdev/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/dreamdev/stable/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by quassy** [comment]
Sorry about that. Sadly they seem to be gone (and will be removed with the next commit).

**Comment by sysfu** [comment]
I emailed the maintainer 'George' about it a few days ago but have yet to hear back.

https://code.launchpad.net/~dreamdev/eradio/translations
