### ISSUE TITLE
Tomato audio alarm no sound

### ISSUE THREAD

**Issue by crisconru** [quassy/elementary-apps#64]
Hi,

first of all, **congratulations for you're job** ;-) 
So I've got problem with the audio, it doesn't sound. I use Elementary OS Freya FYI.
It could be possible to set the audio for stop and restart? That would help me.

Thanks in advance

**Comment by crisconru** [comment]
I've reinstalled twice and reboot, that's fix it.
While it could be possible to configure the ringtones? It would be nice to select music for working time and other music for relax time

**Comment by 1j01** [comment]
You can report a bug related to that specific app [here](https://bugs.launchpad.net/tomatoapp). This is just a collection of third party apps.

**Comment by quassy** [comment]
I'm always happy to help where I can, but what @1j01 said 😉
