### ISSUE TITLE
Mixed colors? red/green

### ISSUE THREAD

**Issue by megatux** [quassy/elementary-apps#72]
v1.0 Is this ok? :/
![captura realizada el 2017-05-23 14 10 48](https://cloud.githubusercontent.com/assets/850020/26366593/031b60b4-3fc2-11e7-9b4c-22bdbf4696c8.png)

**Comment by quassy** [comment]
I don't think this is intended but as I'm only presenting the apps so more people learn about them, not actually developing them I can't fix this. You can find the [bug tracker for Tomato](https://bugs.launchpad.net/tomatoapp) on Launchpad. (I think this is the app you are using, if not feel free to comment again.) Hope this helps.
